<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>bundleUUID</key>
	<string>4F45FDC0-62CA-4786-9134-8BC7C1F5606F</string>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
		<string>z80s</string>
		<string>s</string>
	</array>
	<key>name</key>
	<string>Z80</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>;.*\n</string>
			<key>name</key>
			<string>comment.line.z80</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(adc|add|and|bit|call|ccf|cp|cpd|cpdr|cpi|cpir|cpl|daa|dec|di|djnz|ei|ex|exx|halt|im|in|inc|ind|indr|ini|inir|jp|jr|ld|ldd|lddr|ldi|ldir|neg|nop|or|otdr|otir|outd|outi|out|pop|push|res|ret|reti|retn|rl|rla|rlc|rlca|rld|rr|rra|rrc|rrca|rrd|rst|sbc|scf|set|sla|sll|sra|srl|sub|xor)\b</string>
			<key>name</key>
			<string>keyword.opcode.z80</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(z|nz|c|nc|po|pe|p|m)\b</string>
			<key>name</key>
			<string>constant.language.condition.z80</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(a|af|b|bc|c|d|de|e|h|hl|ix|ixh|ixl|iy|iyh|iyl|l|sp)\b</string>
			<key>name</key>
			<string>constant.language.register.z80</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(align|autoexec|db|defb|dm|defm|defs|defw|ds|dump|dw|else|endif|endm|equ|for|if|ifnb|inc|include|list|local|macro|mdat|next|org|xlist|z80)\b</string>
			<key>name</key>
			<string>keyword.directive.z80</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)^(\s*@?[0-9a-z_.]*:)</string>
			<key>name</key>
			<string>entity.name.function.z80</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\$|@|(@[-+])?[a-z_.]+[0-9a-z_.]*)</string>
			<key>name</key>
			<string>variable.identifier.z80</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(&amp;[0-9a-f]+|0x[0-9a-f]+)</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.z80</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(%[01]+|0b[01]+)</string>
			<key>name</key>
			<string>constant.numeric.integer.binary.z80</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+\b</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.z80</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'(?=.*')</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.z80</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.z80</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pyz80</string>
	<key>uuid</key>
	<string>257683C2-B92A-4742-863F-3FDA5DB0B55F</string>
</dict>
</plist>
